{% set name = "compyle" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/pypr/compyle/archive/{{ version }}.tar.gz
  sha256: efbff7be67d92ff3a3c26b8ef2cfb3e3c3fe83ba57891879df5f3887fedc9105

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - cython
    - mako
    - mock >=1.0
    - numpy
    - python
    - setuptools
    - pytools
    - pip
  run:
    - mako
    - {{ pin_compatible('numpy') }}
    - python
    - pytools

test:
  imports:
    - compyle

about:
  home: https://github.com/pypr/compyle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Execute a subset of Python on HPC platforms
  doc_url: https://compyle.readthedocs.io/

extra:
  recipe-maintainers:
    - rishi9699

