travis:
  secure:
    BINSTAR_TOKEN: scUykd/XxT194HNr6Vua1szMWvq3tBFE2eRHbO6iIhRS4EibjqztGpRYfU951StvRG8Wjj8qu1WPhO1Y29e4Ig807FGDQAKfBzIjYAZe1uHuUEPxeKdPyYlyJZWD5cSOPxGQmsXU4BoqjJlQuXkvi51Eqt662uaKS7pCskog79t945qjKgmePHhdyYPB1u48uTABjphGT63GKpxPdtfcovYOXSXnl5UIhDzfPmrWuAA59eksTEQYUaAVnnCTHevPC3Osl0lDPcRFHq18ZN6Z71TYdJiP0q3uOjc/F0xwTkSXzQHCtcQQTwMT8f5eOSmQN8WljpIaNThgF+n/NRB61ZiWPsIc0/0NL6MzFlgM104wthapRZeOEajnQ/pgoAdJ39MXrkMLkS7U8nP/cTze+Apt3bslUmLnde/h650szvn/h/ye11qtiB2buQQ0LzfsZpvBTRCgEkDWjSuri+Nq14HxOAUa1hRgjs9WEpXUwRLBfTbuV2UBs/JHhm9oLWjK1KDexQ1ZzPPg4SIIMDFFhmqvuCl8iQ4cYWXjqlNL1oRz2n1AlW91rUA7+QyjoAdF6baFOS8Q4XqEAGvkAoRV3DUGK5wl2mMF1W9ecLeVjW7EHejej8gPok+rH6JqK8Mb9FgcjkHFxip5G7Hd19zE3iVOUD72VSpDCMgXl8pbIAA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
