travis:
  secure:
    BINSTAR_TOKEN: ami3PMB8owkEShGAh5CiIyOkIXAwrLA3BLXwUqSu13QU1YgDYBgTY7/fP5ybYi6lFkYEpkv1cByZMNzYICWaHBxLtRm6w0VTrFP0fNfQvNuEX9cxYr43Z1taRlYCAM0JQh3pQGiqlhIHRqj2DjHJT+S1AJ8iDqQ8vWsgLXQDJpSbuLvDJ0JAYPoSECE6ExL1OVeYVWI9R5kQzyRgmOOaTd7q/+2I+Tcsnb4ButsxAYkFte59QTY+6C+mBY9YQYACxh5pB8IEDRh5MhCILaO+2N5/BQimf9g2juBd7BkCOKFaHObFyxw2QT74/qYBeNjEs6u+P+kOSreB0Usjmn7kTc57EUm9WyvaBqkCVA90NlpVMckoDrpqOlLBrGLu6cMWLRoqP94thwC6yvbFFWKN8KzoyAkuD40WmJxAZjN9sSt/K4GZ0UkyqW3yxKFJi91JPXtmMEyVtDiGiIIL+t0r06Wl3dBTyd+HYMLFGQkxsSHaLEeP0L3aZ/NcY05E981b9BqGhh9FljtrR8t2tQjeRLV+GPPfCrTJuaOvC+qC6clWkokqKE9w/ePdM/q1Bagr1kXxsKgJYLyba0i53xedvp7WSWRd1IxUwdAkO5bDn3eQ334VZLT8J6sP+KowQIe1pnIwdB0MHwlm8DQjrsQGQDUxiHqPkLFxNyXKqowLGiA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
